// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVupn-jYYw-1WfmHEH4e4phoEy52P7CxQ',
    appId: '1:352467695509:web:5435214b139017c929689c',
    messagingSenderId: '352467695509',
    projectId: 'rentcarsapp-777a9',
    authDomain: 'rentcarsapp-777a9.firebaseapp.com',
    storageBucket: 'rentcarsapp-777a9.firebasestorage.app',
    measurementId: 'G-B0PBDJQ8B9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACr2SJWDBLH_-WPwCcX36T3i1Hw5svzhI',
    appId: '1:352467695509:android:5b636ea81a3cd22a29689c',
    messagingSenderId: '352467695509',
    projectId: 'rentcarsapp-777a9',
    storageBucket: 'rentcarsapp-777a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2IkG7XgBCJ94yvcEyssJhbtVQmel2x2w',
    appId: '1:352467695509:ios:603dde3c4a3905ee29689c',
    messagingSenderId: '352467695509',
    projectId: 'rentcarsapp-777a9',
    storageBucket: 'rentcarsapp-777a9.firebasestorage.app',
    iosClientId: '352467695509-ulncd7t9f5hkprn21dih583ntlu6g3oa.apps.googleusercontent.com',
    iosBundleId: 'com.example.rentCarApp',
  );
}
